/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ty_android_ndkbuilddemo_NdkBuildDemoLib */

#ifndef _Included_com_ty_android_ndkbuilddemo_NdkBuildDemoLib
#define _Included_com_ty_android_ndkbuilddemo_NdkBuildDemoLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ty_android_ndkbuilddemo_NdkBuildDemoLib
 * Method:    getStringFromLib
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ty_android_ndkbuilddemo_NdkBuildDemoLib_getStringFromLib
  (JNIEnv *, jobject);

/*
 * Class:     com_ty_android_ndkbuilddemo_NdkBuildDemoLib
 * Method:    updateNumber
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_ty_android_ndkbuilddemo_NdkBuildDemoLib_updateNumber
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
